Repository WhiteHyun/smart-locker, pull requests merged in 2021-05, with the labels that each got.

#31 Develop sensor listener
  main.py
  src/page/information_page.py
  src/raspSensor.py
  src/ui.py
  src/utils/discriminate.py
  src/utils/ratchController.py
  src/utils/sensor_listener.py
  src/utils/sql.py
  src/utils/util.py
Labels: enhancement

#34 기능 추가
  main.py
  src/img/settings.png
  src/img/support.png
  src/img/unlock.png
  src/img/unlock_background.png
  src/locker_test.ino
  src/page/admin_page.py
  src/page/delivery_page.py
  src/page/find_page.py
  src/page/information_page.py
  src/page/locker_frame.py
  src/page/process_page.py
  src/page/setting_page.py
  src/page/start_page.py
  src/ui.py
  src/utils/locker_state.py
  src/utils/qrcodes.py
  src/utils/ratchController.py
  src/utils/sql.py
  src/utils/util.py
Labels: enhancement

#41 사물함 크기 조정
  src/custom/button.py
  src/page/delivery_page.py
  src/page/locker_frame.py
Labels: enhancement

#44 Hotfix qrcode
  src/page/find_page.py
  src/page/information_page.py
  src/utils/qrcodes.py
Labels: bug

#45 휴대폰 번호 인식 후 문 열림 수정
  src/page/admin_page.py
  src/page/information_page.py
  src/page/input_frame.py
  src/page/locker_frame.py
  src/page/process_page.py
  src/ui.py
  src/utils/sms.py
Labels: enhancement

#47 Feature/admin setting
  src/page/admin_page.py
  src/page/information_page.py
  src/page/start_page.py
Labels: enhancement

#48 인체감지센서, 효과음용 클래스 베이스 생성
  src/raspSensor.py
  src/utils/rasp_sensor.py
  src/utils/sound.py
Labels: enhancement

#49 화면보호기 구현
  src/img/INU_logo.png
  src/page/admin_page.py
  src/page/delivery_page.py
  src/page/find_page.py
  src/page/information_page.py
  src/page/screensaver_page.py
  src/page/setting_page.py
  src/page/start_page.py
  src/ui.py
  src/utils/rasp_sensor.py
  src/utils/util.py
Labels: enhancement

#50 문 개폐 작동버튼 추가
  src/img/closed.png
  src/img/open.png
  src/page/setting_page.py
Labels: enhancement

#51 상태 판별 방법 수정
  src/page/process_page.py
  src/page/setting_page.py
  src/utils/locker_state.py
Labels: enhancement

#53 아두이노 여러개 사용을 위한 쓰레딩
  main.py
  src/utils/sensor_listener.py
Labels: enhancement

#54 키오스크 UI에 보여지도록 해보자
  src/img/kiosk.png
  src/page/locker_frame.py
Labels: enhancement

#56 문 개폐 후 효과음
  data/closed.wav
  data/opened.wav
  src/utils/ratchController.py
  src/utils/sound.py
Labels: enhancement, good first issue

#55 1.1.0
  data/closed.wav
  data/opened.wav
  main.py
  src/custom/button.py
  src/img/INU_logo.png
  src/img/closed.png
  src/img/kiosk.png
  src/img/open.png
  src/page/admin_page.py
  src/page/delivery_page.py
  src/page/find_page.py
  src/page/information_page.py
  src/page/input_frame.py
  src/page/locker_frame.py
  src/page/process_page.py
  src/page/screensaver_page.py
  src/page/setting_page.py
  src/page/start_page.py
  src/raspSensor.py
  src/ui.py
  src/utils/locker_state.py
  src/utils/rasp_sensor.py
  src/utils/ratchController.py
  src/utils/sensor_listener.py
  src/utils/sms.py
  src/utils/sound.py
  src/utils/util.py
Labels: enhancement

#57 센서값 수신시 오류가 발생하여 thrading모듈 대신 multiprocessing 을 사용
  src/utils/sensor_listener.py
Labels: bug

#58 1.1.1
  src/utils/sensor_listener.py
Labels: bug
